export const projectsStyles = {
  section: 'projects-section container',
  header: 'section-header projects-head',
  eyebrow: 'section-eyebrow',
  grid: 'projects-grid',
  card: 'project-card',
  imageWrapper: 'imageWrapper',
  cover: 'cover',
  projectImg: 'projectImg',
  cardTitle: 'project-card-title',
  cardDescription: 'project-card-description',
  descriptionWrap: 'project-description-wrap',
  cardDescriptionCollapsed: 'project-card-description--collapsed',
  cardDescriptionExpanded: 'project-card-description--expanded',
  descriptionToggle: 'project-description-toggle',
  tags: 'tag-wrap',
  actions: 'project-actions',
} as const
